---@class palette.EditorFields
---@field foreground string Foreground color (text).
---@field weak_foreground string Foreground weak variant compared with bg.
---@field background string Background color.
---@field weak_background string Background weak variant compared with the mode ('dark'|'light') color.
---@field strong_background string Lighter/Darker color based on background hex.
---@field contrast_color string Contrast color (with background).
---@field strong_contrast_color string Secondary contrast color (current line number, etc...).
---@field red string Red color (error msgs...)
---@field green string Green color (success msgs...)
---@field yellow string Yellow color (warn msgs...)
---@field weak_red string Weak red color (error msgs...)
---@field weak_green string Green color (success msgs...)
---@field weak_yellow string Yellow color (warn msgs...)
---@field cyan string Cyan color (when red/green/yellow and it's weaks aren't applicable).
---@field magenta string Magenta color (status line).

---@class palette.SyntaxFields
---@field comment string Comment foreground hex.
---@field keyword string Keyword foreground hex.

---@class palette.RusthemePalette
---@field bold boolean Allow bold text for this entire theme variant.
---@field italic boolean Allow italic text for this entire theme variant.
---@field undercurl boolean Allow undercurl for Spelled text.
---@field editor palette.EditorFields
---@field syntax palette.SyntaxFields
