---@class config.TransparentTriggers Control transparent bg.
---@field background boolean Turn main bg into transparent.
---@field float_background boolean Turn floating window bg into transparent.

---@class config.GlobalsConfig
---@field bolds boolean Global bold trigger.
---@field italics boolean Global italic trigger.
---@field transparents config.TransparentTriggers
---@field invert_title boolean Invert title color (bg/fg).
---@field termguicolors boolean

---@class config.MappingOverrides A set of mappings to override each one of the colorscheme variants (`everything` field contains the highest priority).
---@field everything mapping.RusthemeMapping Overrides all variants.
---@field ["core-dark"] mapping.RusthemeMapping Overrides `core-dark`'s variant only.
---@field ["core-light"] mapping.RusthemeMapping Overrides `core-light`'s variant only.
---@field ["mangrove-dark"] mapping.RusthemeMapping Overrides `mangrove-dark`'s variant only.
---@field ["mangrove-light"] mapping.RusthemeMapping Overrides `mangrove-light`'s variant only.

---@class config.RusthemeConfig Rustheme global config.
---@field globals config.GlobalsConfig Targets the colorscheme entirely.
---@field mapping_overrides config.MappingOverrides Overrides specific color palettes.
---@field groups_override table Overrides the group properties (key values must be a table).

---@class mapping.Core Map for neovim core (bg, fg, borders, etc...).
---@field background string Background color.
---@field foreground string Foreground color.
---@field border string Border foreground color.
---@field title string Title foreground color (turns into background color if `mapping.RusthemeMapping.invert_title` is enable).
---@field float_background string|nil Float window background color (`nil` means a bit darker than `background`).
---@field inactive_foreground string Foreground color for inactive text.
---@field cursor_bg string Background color for cursor.
---@field cursor_fg string Foreground color for cursor.
---@field cursor_column string|nil Background for cursor column (when `cursorcolumn` is set. `nil` means weak than cursor bg).
---@field match_paren string Background color for matching parentheses (`()`, `{}`, ...).
---@field current_search string Background color for neovim text search.
---@field non_current_search string Background color for neovim text search (not the current item).
---@field substitute string Background color for neovim text substitution (aka `s:from/to/[OPTIONS]` command).
---@field visual_selection string Background color for neovim text selection (visual mode).
---@field line_number string Foreground color for all line numbers.
---@field current_line_number string Foreground color for the current line number.
---@field window_separator_fg string Foreground color for the window separator.
---@field window_separator_bg string Background color for the window separator.
---@field folded string Background color for the folded lines.
---@field non_text string|nil Foreground color for the NonText & EndOfBuffer (`nil` means `NONE` - invisible).
---@field terminal string Foreground color for terminal text.

---@class mapping.Diff Map for difs (git).
---@field added string Foreground color for added lines in a diff.
---@field removed string Foreground color for removed lines in a diff.
---@field changed string Foreground color for changed lines in a diff.
---@field diff_add string Background color for Diff mode (added line).
---@field diff_delete string Background color for Diff mode (deleted line).
---@field diff_change string Background color for Diff mode (changed line).
---@field diff_text string Background color for Diff mode (diff text within a changed line).
---@field diff_text_add string Background color for Diff mode (added text within a changed line).

---@class mapping.Diagnostic Map for diag. messages.
---@field error string Foreground color for error messages.
---@field warn string Foreground color for warning messages.
---@field question string Foreground color for question messages.

---@class mapping.Status Map for status line colors.
---@field background string StatusLine background color.
---@field normal string StatusLine background color for normal tag.
---@field insert string StatusLine background color for insert tag.
---@field visual string StatusLine background color for visual tag.
---@field replace string StatusLine background color for replace tag.
---@field command string StatusLine background color for command tag.
---@field terminal string StatusLine background color for terminal tag.

---@class mapping.Spell Map text spelling.
---@field spell_bad string Bad spelling undercurl color.
---@field spell_cap string Capital expected spelling undercurl color.
---@field spell_local string Other region spelling undercurl color.
---@field spell_rare string Rarely used spelling undercurl color.

---@class mapping.Pmenu Pmenu mapping.
---@field foreground string Pmenu foreground color.
---@field background string Pmenu background color.
---@field selection string Pmenu selection background color.
---@field scroll_bar string Pmenu scroll bar background color.
---@field thumb string Pmenu thumb background color.
---@field wild_menu string Wild menu current completion background color.

---@class mapping.Syntax Syntax color mapping.
---@field comment string Comment's foreground color.
---@field constant string Constant's foreground color.
---@field str string String's foreground color.
---@field charac string|nil Char's foreground color (`nil` means same as `str`).
---@field integer string Integer's foreground color.
---@field float string Float's foreground color (`nil` means same as `integer`).
---@field boolean string Boolean's foreground color.
---@field variable string Variable's foreground color.
---@field function string Function's foreground color.
---@field keyword string Keyword's foreground color.
---@field operator string Operator's foreground color.
---@field annotation string Annotation's foreground color.
---@field type string Type's foreground color.
---@field underline string Underline's foreground color.

---@class mapping.LSP LSP color mapping.
---@field error string Foreground color for lsp error.
---@field warn string Foreground color for lsp warning.
---@field hint string Foreground color for lsp hint.
---@field info string Foreground color for lsp info.
---@field ok string Foreground color for lsp ok.
---@field code_lens string Foreground color for lsp code lens.

---@class mapping.RusthemeMapping Map the neovim token context to a palette color. Also holds global triggers (bold, italic, ...)
---@field bolds? boolean Allow bold text for this entire theme variant.
---@field italics? boolean Allow italic text for this entire theme variant.
---@field transparents? config.TransparentTriggers
---@field invert_title? boolean Invert title color (bg/fg).
---@field termguicolors? boolean
---@field core? mapping.Core
---@field status? mapping.Status
---@field pmenu? mapping.Pmenu
---@field diff? mapping.Diff
---@field diagnostic? mapping.Diagnostic
---@field spelling? mapping.Spell
---@field syntax? mapping.Syntax
---@field lsp? mapping.LSP
